package output

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/livepeer/clearinghouse/auth0-provisioner/internal/auth0"
)

// BuildEnvFile renders the provisioning result as a .env file: shared tenant
// settings, identity-webhook hints, and one block per app pair carrying the
// public client id and the M2M id + secret. The output contains secrets.
func BuildEnvFile(result *auth0.Result) string {
	var b strings.Builder

	b.WriteString("# Generated by auth0ctl — contains secrets, do not commit\n\n")

	b.WriteString("# Auth0 tenant (shared)\n")
	fmt.Fprintf(&b, "AUTH0_DOMAIN=%s\n", result.Domain)
	fmt.Fprintf(&b, "AUTH0_ISSUER=%s\n", result.Issuer)
	fmt.Fprintf(&b, "AUTH0_JWKS_URL=%s\n", result.JwksURL)

	b.WriteString("\n# Identity webhook (token azp = public client id)\n")
	fmt.Fprintf(&b, "JWKS_URL=%s\n", result.JwksURL)
	fmt.Fprintf(&b, "JWT_ISSUER=%s\n", result.Issuer)
	b.WriteString("CLAIM_CLIENT_ID=azp\n")
	b.WriteString("USAGE_SUBJECT_TYPE=auth0_user_id\n")

	for _, app := range result.Apps {
		prefix := envPrefix(app.Name)
		fmt.Fprintf(&b, "\n# %s\n", app.Name)
		fmt.Fprintf(&b, "%s_AUTH0_AUDIENCE=%s\n", prefix, app.Audience)
		fmt.Fprintf(&b, "%s_AUTH0_PUBLIC_CLIENT_ID=%s\n", prefix, app.PublicClientID)
		fmt.Fprintf(&b, "%s_AUTH0_M2M_CLIENT_ID=%s\n", prefix, app.M2MClientID)
		fmt.Fprintf(&b, "%s_AUTH0_M2M_CLIENT_SECRET=%s\n", prefix, app.M2MClientSecret)
	}

	return b.String()
}

var nonAlnum = regexp.MustCompile(`[^A-Z0-9]+`)

// envPrefix turns an app name into an uppercase, underscore-delimited env prefix
// (e.g. "Per-User App" → "PER_USER_APP").
func envPrefix(name string) string {
	up := nonAlnum.ReplaceAllString(strings.ToUpper(name), "_")
	return strings.Trim(up, "_")
}
