package output

import (
	"fmt"
	"strings"

	"github.com/livepeer/clearinghouse/internal/auth0"
	"github.com/livepeer/clearinghouse/internal/config"
)

func BuildEnvFile(cfg *config.BootstrapConfig, auth0Result *auth0.ProvisionResult) string {
	var b strings.Builder

	b.WriteString("# Generated by clearinghouse-bootstrap\n")
	b.WriteString("# VM runtime: deploy/docker-compose.yml | Vercel platform: sdk-config.json\n\n")

	if auth0Result != nil {
		b.WriteString("# Auth0\n")
		fmt.Fprintf(&b, "AUTH0_DOMAIN=%s\n", cfg.Auth0Domain)
		fmt.Fprintf(&b, "AUTH0_ISSUER=%s\n", auth0Result.Issuer)
		fmt.Fprintf(&b, "AUTH0_JWKS_URL=%s\n", auth0Result.JwksURL)
		fmt.Fprintf(&b, "AUTH0_AUDIENCE=%s\n", auth0Result.APIIdentifier)
		fmt.Fprintf(&b, "AUTH0_PUBLIC_CLIENT_ID=%s\n", auth0Result.PublicClientID)
		fmt.Fprintf(&b, "AUTH0_M2M_CLIENT_ID=%s\n", auth0Result.M2MClientID)
		fmt.Fprintf(&b, "AUTH0_M2M_CLIENT_SECRET=%s\n", auth0Result.M2MClientSecret)
		b.WriteString("\n# Identity webhook (Vercel platform — builder-sdk/signer/webhook)\n")
		fmt.Fprintf(&b, "JWKS_URL=%s\n", auth0Result.JwksURL)
		fmt.Fprintf(&b, "JWT_ISSUER=%s\n", auth0Result.Issuer)
		fmt.Fprintf(&b, "JWT_AUDIENCE=%s\n", auth0Result.APIIdentifier)
		fmt.Fprintf(&b, "WEBHOOK_SECRET=%s\n", cfg.WebhookSecret)
		b.WriteString("CLAIM_CLIENT_ID=azp\n")
		b.WriteString("USAGE_SUBJECT_TYPE=auth0_user_id\n\n")
	}

	if !cfg.SkipOpenMeter {
		b.WriteString("# Konnect Metering & Billing\n")
		fmt.Fprintf(&b, "OPENMETER_URL=%s\n", strings.TrimSuffix(cfg.OpenmeterURL, "/"))
		if cfg.OpenmeterAPIKey != "" {
			fmt.Fprintf(&b, "OPENMETER_API_KEY=%s\n", cfg.OpenmeterAPIKey)
		}
		fmt.Fprintf(&b, "OPENMETER_TRIAL_FEATURE_KEY=%s\n\n", cfg.TrialFeatureKey)
	}

	b.WriteString("# Vercel platform URLs (update after platform deploy)\n")
	fmt.Fprintf(&b, "REMOTE_SIGNER_WEBHOOK_URL=%s\n", cfg.RemoteSignerWebhookURL)
	fmt.Fprintf(&b, "SIGNER_PROXY_URL=%s\n", cfg.SignerProxyURL)
	fmt.Fprintf(&b, "SIGNER_PUBLIC_URL=%s\n\n", cfg.SignerPublicURL)

	b.WriteString("# Kafka (docker compose service name)\n")
	fmt.Fprintf(&b, "KAFKA_BROKERS=%s\n", cfg.KafkaBrokers)
	fmt.Fprintf(&b, "KAFKA_GATEWAY_TOPIC=%s\n\n", cfg.KafkaGatewayTopic)

	b.WriteString("# OpenMeter Collector (Wei -> USD micros)\n")
	fmt.Fprintf(&b, "ETH_USD_PRICE=%s\n\n", cfg.EthUsdPrice)

	b.WriteString("# Remote signer (operator — fund ETH account before stack:up)\n")
	fmt.Fprintf(&b, "SIGNER_NETWORK=%s\n", cfg.SignerNetwork)
	fmt.Fprintf(&b, "ETH_RPC_URL=%s\n", cfg.EthRPCURL)
	if cfg.SignerEthAddr != "" {
		fmt.Fprintf(&b, "SIGNER_ETH_ADDR=%s\n", cfg.SignerEthAddr)
	} else {
		b.WriteString("# SIGNER_ETH_ADDR=0x...\n")
	}

	b.WriteString("\n# VM deploy: clearinghouse-bootstrap + docker compose\n")
	b.WriteString("# Platform deploy: use sdk-config.json on Vercel (webhook route + signer proxy)\n")

	return b.String()
}
