package output

import (
	"fmt"
	"strings"

	"github.com/livepeer/clearinghouse/internal/auth0"
	"github.com/livepeer/clearinghouse/internal/config"
)

func BuildEnvFile(cfg *config.BootstrapConfig, auth0Result *auth0.ProvisionResult) string {
	var b strings.Builder

	b.WriteString("# Generated by clearinghouse-bootstrap\n")
	b.WriteString("# Platform deploy: sdk-config.json | VM runtime: see deploy stack\n\n")

	if auth0Result != nil {
		b.WriteString("# Auth0\n")
		fmt.Fprintf(&b, "AUTH0_DOMAIN=%s\n", cfg.Auth0Domain)
		fmt.Fprintf(&b, "AUTH0_ISSUER=%s\n", auth0Result.Issuer)
		fmt.Fprintf(&b, "AUTH0_JWKS_URL=%s\n", auth0Result.JwksURL)
		fmt.Fprintf(&b, "AUTH0_AUDIENCE=%s\n", auth0Result.APIIdentifier)
		fmt.Fprintf(&b, "AUTH0_PUBLIC_CLIENT_ID=%s\n", auth0Result.PublicClientID)
		fmt.Fprintf(&b, "AUTH0_M2M_CLIENT_ID=%s\n", auth0Result.M2MClientID)
		fmt.Fprintf(&b, "AUTH0_M2M_CLIENT_SECRET=%s\n", auth0Result.M2MClientSecret)
		b.WriteString("\n# Identity webhook (Vercel platform — builder-sdk/signer/webhook)\n")
		fmt.Fprintf(&b, "JWKS_URL=%s\n", auth0Result.JwksURL)
		fmt.Fprintf(&b, "JWT_ISSUER=%s\n", auth0Result.Issuer)
		fmt.Fprintf(&b, "JWT_AUDIENCE=%s\n", auth0Result.APIIdentifier)
		fmt.Fprintf(&b, "WEBHOOK_SECRET=%s\n", cfg.WebhookSecret)
		b.WriteString("CLAIM_CLIENT_ID=azp\n")
		b.WriteString("USAGE_SUBJECT_TYPE=auth0_user_id\n\n")
	}

	if !cfg.SkipOpenMeter {
		b.WriteString("# Konnect Metering & Billing\n")
		fmt.Fprintf(&b, "OPENMETER_URL=%s\n", strings.TrimSuffix(cfg.OpenmeterURL, "/"))
		if cfg.OpenmeterAPIKey != "" {
			fmt.Fprintf(&b, "OPENMETER_API_KEY=%s\n", cfg.OpenmeterAPIKey)
		}
		fmt.Fprintf(&b, "OPENMETER_TRIAL_FEATURE_KEY=%s\n", cfg.TrialFeatureKey)
	}

	return b.String()
}
